from aiogram.dispatcher.filters.state import StatesGroup, State


class NewRawMeatBatchForm(StatesGroup):
    set_wait = State()
    set_check = State()
    set_photo_ypd = State()
    set_photo_acceptance_certificate = State()
    set_photo_ttn = State()
    set_number_ttn = State()
    set_photo_tn = State()
    set_photo_vet = State()
    set_link_vet = State()
    set_company = State()
    set_photo_ref_truck = State()
    set_photo_body_temperature_truck = State()
    set_body_temperature_truck = State()
    set_manufacture_date = State()
    set_raw_material = State()
    set_ttntype_raw_material = State()
    set_condition = State()
    set_organization = State()
    set_choice_vet_doc = State()
    set_photo_temperature = State()
    set_temperature = State()
    set_photo_pallet = State()
    set_weight = State()
    set_tags_number = State()
    set_buh_accounting = State()
