# Generated by Django 4.2.10 on 2024-02-21 20:43

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BufferPalletMars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('pallet_id', models.IntegerField(verbose_name='ID паллета')),
                ('box_count', models.IntegerField(verbose_name='Кол-во ящиков')),
                ('brutto_weight', models.FloatField(verbose_name='Вес брутто')),
                ('netto_weight', models.FloatField(verbose_name='Вес нетто')),
                ('pallet_weight', models.FloatField(verbose_name='Вес паллета')),
            ],
            options={
                'verbose_name': 'Паллеты с остатками от фарша Марс',
                'verbose_name_plural': 'Паллеты с остатками от фарша Марс',
                'db_table': 'buffer_pallets_mars',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guid', models.CharField(max_length=1000)),
                ('issuerid', models.CharField(max_length=1000)),
                ('apikey', models.CharField(max_length=1000)),
                ('api_login', models.CharField(max_length=255)),
                ('api_pass', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeatBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('production_id', models.CharField(max_length=255, verbose_name='ID заготовки')),
                ('protein', models.FloatField(default=0, verbose_name='Белки')),
                ('fat', models.FloatField(default=0, verbose_name='Жиры')),
                ('moisture', models.FloatField(default=0, verbose_name='Влага')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата прихода в цех')),
                ('type_meat_blank', models.IntegerField(verbose_name='Заготовка МКО')),
                ('weight', models.FloatField(default=0, verbose_name='Вес заготовки')),
                ('weight_receipt', models.FloatField(default=0, verbose_name='Вес заготовки')),
            ],
            options={
                'verbose_name': 'заготовка',
                'verbose_name_plural': 'заготовки',
                'db_table': 'meat_blank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MincedMeatBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('production_id', models.CharField(max_length=255, verbose_name='ID заготовки')),
                ('number_mix', models.IntegerField(verbose_name='предполагаемое количество замесов')),
                ('protein', models.FloatField(verbose_name='Белки')),
                ('fat', models.FloatField(verbose_name='Жиры')),
                ('is_night', models.BooleanField(default=False, verbose_name='Ночная смена')),
                ('line_type', models.SmallIntegerField(null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('moisture', models.FloatField(verbose_name='Влага')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата прихода в цех')),
            ],
            options={
                'verbose_name': 'Фарш',
                'verbose_name_plural': 'Фарш',
                'db_table': 'minced_meat_batch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MincedMeatBatchMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('production_id', models.CharField(max_length=255)),
                ('line_type', models.SmallIntegerField(default=None, null=True)),
                ('minced_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='CRM.mincedmeatbatch')),
            ],
            options={
                'verbose_name': 'Склад ГП',
                'verbose_name_plural': 'Склад ГП',
                'db_table': 'minced_meat_batch_mix',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Должность')),
                ('code_name', models.CharField(default=None, max_length=50, verbose_name='кодовое название должности')),
            ],
            options={
                'verbose_name': 'Должности',
                'verbose_name_plural': 'Должности',
                'db_table': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'виды сырья',
                'verbose_name_plural': 'виды сырья',
                'db_table': 'raw_material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RawMeatBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('production_id', models.CharField(max_length=100, verbose_name='ID партии')),
                ('photo_ref_truck', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('photo_body_temperature_truck', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('body_temperature_truck', models.CharField(max_length=255, null=True, verbose_name='температура в кузове в момент открытия машины')),
                ('photo_ypd', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch', verbose_name='Редактирование фото УПД')),
                ('photo_acceptance_certificate', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('acceptance_certificate', models.FileField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('photo_ttn', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('date_ttn', models.DateTimeField(null=True)),
                ('number_ttn', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер ТТН')),
                ('link_vet', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Ссылка на ЭВСД')),
                ('photo_tn', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('photo_vet', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('document_number_vet', models.CharField(max_length=255, null=True)),
                ('document_date_vet', models.CharField(max_length=255, null=True)),
                ('manufacture_date_vet', models.CharField(max_length=255, null=True, verbose_name='дата производства')),
                ('expiration_date_vet', models.CharField(max_length=255, null=True)),
                ('weight_vet', models.FloatField(null=True)),
                ('organization_vet', models.CharField(max_length=600, null=True)),
                ('organization', models.CharField(max_length=600, null=True, verbose_name='поставщик')),
                ('manufacturer', models.CharField(max_length=600, null=True, verbose_name='производитель')),
                ('condition', models.CharField(max_length=255)),
                ('photo_temperature', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('temperature', models.CharField(max_length=255, null=True)),
                ('photo_pallet', models.ImageField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('weight', models.FloatField(verbose_name='Оставшийся вес')),
                ('weight_receipt', models.FloatField(null=True, verbose_name='Вес поступления')),
                ('tags_number', models.IntegerField()),
                ('is_future_batch', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.company', verbose_name='Компания')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.rawmaterial', verbose_name='тип сырья')),
            ],
            options={
                'verbose_name': 'сырье',
                'verbose_name_plural': 'сырье',
                'db_table': 'raw_meat_batch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название рецепта')),
            ],
            options={
                'verbose_name': 'Рецепты',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'recipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecondMincedMeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('type', models.SmallIntegerField()),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('production_id', models.CharField(default='', max_length=255)),
                ('additional_data', models.JSONField(null=True, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Вторфарш',
                'verbose_name_plural': 'Вторфарш',
                'db_table': 'second_minced_meat',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('customer', models.CharField(max_length=255, verbose_name='Кому отгрузили')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'db_table': 'shipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShockerCamera',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('shocker_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Номер шокера')),
                ('max_pallet_count', models.IntegerField(default=100, verbose_name='Максимальное кол-во паллетов в камере')),
            ],
            options={
                'verbose_name': 'Настройка шокеров',
                'verbose_name_plural': 'Настройка шокеров',
                'db_table': 'shock_camera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('codename', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.BigIntegerField(verbose_name='TGid планшета')),
                ('name', models.CharField(max_length=50, verbose_name='Пользователь за которым закреплен планшет')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Telegram аккаунты',
                'verbose_name_plural': 'Telegram аккаунты',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='TotalMincedMeatBatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('additional_data', models.JSONField(null=True)),
                ('minced_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='CRM.mincedmeatbatch')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.status')),
            ],
            options={
                'db_table': 'minced_meat_batch_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tilers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.BooleanField(default=True)),
                ('minced_meat_batch_mix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='CRM.mincedmeatbatchmix')),
            ],
            options={
                'db_table': 'tilers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShockerMixLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('additional_data', models.JSONField(null=True, verbose_name='Доп. данные')),
                ('status_unload', models.BooleanField(default=False, verbose_name='Статус отгрузки')),
                ('minced_meat_batch_mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mix', to='CRM.mincedmeatbatchmix', verbose_name='Фарш')),
                ('second_minced_meat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_meat', to='CRM.secondmincedmeat', verbose_name='Вторфарш')),
                ('shocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shocker', to='CRM.shockercamera', verbose_name='Номер шокера')),
            ],
            options={
                'verbose_name': 'Загрузки в шокере',
                'verbose_name_plural': 'Загрузки в шокере',
                'db_table': 'shocker_mix_pallet_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShipmentPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('number', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('minced_meat_batch_mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_pallets', to='CRM.mincedmeatbatchmix')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='CRM.shipment')),
            ],
            options={
                'db_table': 'shipment_pallet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecondMincedMeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('additional_data', models.JSONField(null=True)),
                ('second_minced_meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='CRM.secondmincedmeat')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.status')),
            ],
            options={
                'db_table': 'second_minced_meat_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecondMincedMeatBatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255)),
                ('file_location', models.FileField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='photo_marked_and_storing_second_meat')),
                ('second_minced_meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.secondmincedmeat')),
            ],
            options={
                'db_table': 'second_minced_meat_batch_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RawMeatBatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('additional_data', models.JSONField(null=True)),
                ('raw_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='CRM.rawmeatbatch')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.status')),
            ],
            options={
                'db_table': 'raw_meat_batch_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RawMeatBatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255)),
                ('file_location', models.FileField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='raw_meat_batch')),
                ('raw_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='CRM.rawmeatbatch')),
            ],
            options={
                'db_table': 'raw_meat_batch_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RawMaterialParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('defrost', models.FloatField(default=100, verbose_name='Значение дефростации (в процентах)')),
                ('second_minced_meat_exit', models.FloatField(default=100, verbose_name='Выход вторфаша (в процентах)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material', to='CRM.rawmaterial', verbose_name='Сырье')),
            ],
            options={
                'verbose_name': 'Параметры сырья',
                'verbose_name_plural': 'Параметры сырья',
                'db_table': 'material_parameters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MincedMeatBatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('additional_data', models.JSONField(null=True)),
                ('notify', models.BooleanField(default=False)),
                ('minced_meat_batch_mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='CRM.mincedmeatbatchmix')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.status')),
            ],
            options={
                'db_table': 'minced_meat_batch_mix_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MincedMeatBatchSecondMeatBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('weight', models.FloatField()),
                ('minced_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_minced_meat', to='CRM.mincedmeatbatch')),
                ('second_minced_meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.secondmincedmeat')),
            ],
            options={
                'db_table': 'minced_meat_batch_second_meat_blank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MincedMeatBatchRawMeatBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('weight', models.FloatField()),
                ('minced_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_meat_batches', to='CRM.mincedmeatbatch')),
                ('raw_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.rawmeatbatch')),
            ],
            options={
                'db_table': 'minced_meat_batch_raw_meat_batch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MincedMeatBatchMeatBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('weight', models.FloatField()),
                ('meat_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.meatblank')),
                ('minced_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_blanks', to='CRM.mincedmeatbatch')),
            ],
            options={
                'db_table': 'minced_meat_batch_meat_blank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MincedMeatBatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255)),
                ('file_location', models.FileField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='backend-private'), upload_to='photo_marked_and_storing')),
                ('minced_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.mincedmeatbatch')),
            ],
            options={
                'db_table': 'minced_meat_batch_file',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mincedmeatbatch',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.recipe', verbose_name='рецепт'),
        ),
        migrations.CreateModel(
            name='MeatBlankStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('additional_data', models.JSONField(null=True)),
                ('notify', models.BooleanField(default=False)),
                ('meat_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='CRM.meatblank')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.status')),
            ],
            options={
                'db_table': 'meat_blank_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeatBlankRawMeatBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('weight', models.FloatField()),
                ('meat_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_blanks', to='CRM.meatblank')),
                ('raw_meat_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_meat_batches', to='CRM.rawmeatbatch')),
            ],
            options={
                'db_table': 'meat_blank_raw_meat_batches',
                'managed': True,
            },
        ),
    ]
