# Generated by Django 4.2.10 on 2024-02-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MincedStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('protein_deviation_minus', models.FloatField(default=0, verbose_name='Отклонение белков -')),
                ('protein', models.FloatField(verbose_name='Значение массовой доли белков')),
                ('protein_deviation_plus', models.FloatField(default=0, verbose_name='Отклонение белков +')),
                ('fats_deviation_minus', models.FloatField(default=0, verbose_name='Отклонение жиров -')),
                ('fats', models.FloatField(verbose_name='Значение массовой доли жиров')),
                ('fats_deviation_plus', models.FloatField(default=0, verbose_name='Отклонение жиров +')),
                ('moisture_deviation_minus', models.FloatField(default=0, verbose_name='Отклонение влаги - ')),
                ('moisture', models.FloatField(verbose_name='Значение массовой доли влаги')),
                ('moisture_deviation_plus', models.FloatField(default=0, verbose_name='Отклонение влаги +')),
                ('pitch_deviation_minus', models.FloatField(blank=True, default=0, verbose_name='Отклонение смоле -')),
                ('pitch', models.FloatField(blank=True, verbose_name='Отклонение по смоле')),
                ('pitch_deviation_plus', models.FloatField(blank=True, default=0, verbose_name='Отклонение смоле +')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeName', to='CRM.recipe', verbose_name='Название рецепта')),
            ],
            options={
                'verbose_name': 'Эталонные значения фарша',
                'verbose_name_plural': 'Эталонные значения фарша',
                'db_table': 'minced_standards',
            },
        ),
    ]
