# Generated by Django 4.2.10 on 2024-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_mincedstandards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmeatbatch',
            name='tags_number',
            field=models.IntegerField(verbose_name='Кол-во бирок'),
        ),
    ]
