# Generated by Django 4.2.10 on 2024-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_rawmeatbatch_tags_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmeatbatch',
            name='condition',
            field=models.CharField(choices=[('frozen', 'Замороженное'), ('chilled', 'Охлажденное')], max_length=255, verbose_name='Кондиция'),
        ),
    ]
