# Generated by Django 4.2.10 on 2024-06-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_rawmeatbatch_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTNType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тип сырья',
                'verbose_name_plural': 'Тип сырья',
                'db_table': 'ttn_raw_material_type',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rawmeatbatch',
            name='ttn_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.ttntype', verbose_name='Наименование номенклатуры'),
        ),
    ]
