# Generated by Django 4.2.10 on 2024-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_ttntype_rawmeatbatch_ttn_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttntype',
            options={'managed': True, 'verbose_name': 'Номенклатуры сырья', 'verbose_name_plural': 'Номенклатуры сырья'},
        ),
        migrations.AlterField(
            model_name='ttntype',
            name='custom',
            field=models.BooleanField(default=False, verbose_name='Добавлено через бота'),
        ),
        migrations.AlterField(
            model_name='ttntype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ttntype',
            name='type',
            field=models.CharField(help_text='Должно быть на английском', max_length=255, verbose_name='Кодовое название'),
        ),
    ]
