# Generated by Django 4.2.10 on 2024-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_alter_ttntype_options_alter_ttntype_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mincedmeatbatch',
            name='raw_meat_batchesss',
            field=models.ManyToManyField(blank=True, to='CRM.mincedmeatbatchrawmeatbatch'),
        ),
    ]
