# Generated by Django 4.2.10 on 2024-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_mincedmeatbatch_raw_meat_batchesss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mincedmeatbatch',
            name='raw_meat_batchesss',
        ),
        migrations.AddField(
            model_name='mincedmeatbatch',
            name='raw_meat_batches_for_edit',
            field=models.ManyToManyField(blank=True, to='CRM.mincedmeatbatchrawmeatbatch'),
        ),
    ]
