# Generated by Django 4.2.10 on 2024-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_remove_mincedmeatbatch_raw_meat_batchesss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mincedmeatbatchrawmeatbatch',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
