# Generated by Django 4.2.10 on 2024-07-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_alter_mincedmeatbatchrawmeatbatch_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mincedmeatbatchrawmeatbatch',
            name='minced_meat_batch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_meat_batches', to='CRM.mincedmeatbatch'),
        ),
        migrations.AlterField(
            model_name='mincedmeatbatchrawmeatbatch',
            name='raw_meat_batch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.rawmeatbatch'),
        ),
    ]
