# Generated by Django 4.2.10 on 2024-07-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_mincedmeatbatchrawmeatbatch_minced_meat_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meatblankrawmeatbatch',
            name='meat_blank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_blanks', to='CRM.meatblank', verbose_name='Фарш'),
        ),
        migrations.AlterField(
            model_name='meatblankrawmeatbatch',
            name='raw_meat_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_meat_batches', to='CRM.rawmeatbatch', verbose_name='Партия'),
        ),
    ]
