# Generated by Django 4.2.10 on 2024-07-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_alter_meatblankrawmeatbatch_meat_blank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meatblankrawmeatbatch',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
