# Generated by Django 4.2.10 on 2024-07-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_alter_meatblankrawmeatbatch_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mincedmeatbatch',
            name='raw_meat_batches_for_edit',
        ),
    ]
