# Generated by Django 4.2.10 on 2024-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_remove_mincedmeatbatch_raw_meat_batches_for_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mincedstandards',
            name='pitch_deviation_minus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Отклонение смоле -'),
        ),
    ]
