# Generated by Django 4.2.10 on 2024-10-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_alter_mincedstandards_pitch_deviation_minus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mincedmeatbatchmix',
            name='remake',
            field=models.BooleanField(default=False),
        ),
    ]
