# Generated by Django 4.2.10 on 2024-10-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_mincedmeatbatchmix_remake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mincedmeatbatchmeatblank',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='mincedmeatbatchsecondmeatblank',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
