# Generated by Django 4.2.10 on 2024-10-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_alter_mincedmeatbatchmeatblank_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tilers',
            options={'managed': True, 'verbose_name': 'Плиточник', 'verbose_name_plural': 'Плиточники'},
        ),
        migrations.AlterField(
            model_name='tilers',
            name='minced_meat_batch_mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='CRM.mincedmeatbatchmix', verbose_name='Замес'),
        ),
        migrations.AlterField(
            model_name='tilers',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Занят'),
        ),
    ]
