# Generated by Django 4.2.10 on 2024-10-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_alter_tilers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilers',
            name='minced_meat_batch_mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixes', to='CRM.mincedmeatbatchmix', verbose_name='Замес'),
        ),
    ]
