# Generated by Django 4.2.10 on 2024-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_alter_tilers_minced_meat_batch_mix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilers',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Свободен'),
        ),
    ]
