# Generated by Django 4.2.10 on 2024-11-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_warehouseresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseresponse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='warehouseresponse',
            name='updated_at',
        ),
    ]
