# Generated by Django 4.2.10 on 2024-11-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0021_remove_warehouseresponse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseresponse',
            name='date',
        ),
        migrations.AddField(
            model_name='warehouseresponse',
            name='res_date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
