# Generated by Django 4.2.10 on 2024-11-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0022_remove_warehouseresponse_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.DateField(null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'warehouse_responses',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='WarehouseResponse',
        ),
    ]
