# Generated by Django 4.2.10 on 2024-11-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_warehouseresponses_delete_warehouseresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseresponses',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
