# Generated by Django 4.2.10 on 2025-02-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0024_alter_warehouseresponses_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mincedmeatbatch",
            name="is_shocker",
            field=models.BooleanField(default=False, verbose_name="Проходит по шокеру?"),
        ),
        migrations.AlterField(
            model_name="mincedmeatbatchmix",
            name="minced_meat_batch",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="mixes", to="CRM.mincedmeatbatch"
            ),
        ),
        migrations.AlterField(
            model_name="secondmincedmeatbatchfile",
            name="second_minced_meat",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="CRM.secondmincedmeat"),
        ),
    ]
