DEFAULT_STATUS_LIST = (
    {"codename": "unloading_kt2", "name": "Растаривание КТ2"},
    {"codename": "unloading_secondary", "name": "Растаривание вторичной пары"},
    {"codename": "laboratory_separation", "name": "Сепарация для анализа"},
    {"codename": "defrosting", "name": "Взвешивание после дефростации"},
    {"codename": "to_defroster", "name": "Погрузка в дефростер"},
    {"codename": "start_mix", "name": "Начало перемешивания"},
    {"codename": "mix_analyze", "name": "Анализ замеса"},
    {"codename": "mix_export", "name": "Выгрузка замеса"},
    {"codename": "to_tiler", "name": "Загрузка в плиточник (1-14)"},
    {"codename": "to_shocker", "name": "Загрузка в шокер"},
    {"codename": "to_shocker_finish", "name": "Загрузка в шокер завершена"},
    {"codename": "raw_meat_batch_weighing", "name": "Взвешивание сырья"},
    {"codename": "separation", "name": "Сепарирование"},
    {"codename": "mix_minced_mmo", "name": "Перемешивание фарша ММО"},
    {"codename": "mix_minced_mko", "name": "Перемешивание фарша МКО"},
    {"codename": "freezing_in_tiler", "name": "Заморозка в плиточнике"},
    {"codename": "aftercooling", "name": "Доохлаждение"},
    {"codename": "packing_minced_meat", "name": "Фасовка готовой фаршемассы"},
    {"codename": "forming_briquettes", "name": "Формирование брикетов"},
    {"codename": "freezing_in_shocker", "name": "Заморозка в шокере"},
    {"codename": "metal_detection", "name": "Металлодетекция"},
    {"codename": "palletizing", "name": "Паллетирование и маркировка"},
    {"codename": "palletizing_end", "name": "Паллетирование и маркировка завершена"},
    {"codename": "pallet_weighing", "name": "Взвешивание палетов"},
    {"codename": "storage", "name": "Хранение на складе для ГП"},
    {"codename": "shipment", "name": "Отгрузка ГП"},
    {"codename": "actual_weight_confirmation", "name": "Подтверждение реального веса заготовки"},
    {"codename": "rastarshik_unload_meat_blank", "name": "Растарка заготовки"},
    {"codename": "rastarshik_unload_meat_blank_end", "name": "Растарка заготовки завершена"},
    {"codename": "unloaded_to_packer", "name": "Выгрузка из плиточника"},
    {"codename": "unloaded_to_packer_end", "name": "Выгрузка из плиточника завершена"},
    {"codename": "unload_shocker", "name": "Выгрузка из шокера"},
    {"codename": "unload_shocker_finish", "name": "Выгрузка из шокера завершена"},
    {"codename": "work_is_finished", "name": "Работа с продуктом завершена"},
    {"codename": "loaded_to_defroster", "name": "Загружено в дефростер"},
    {"codename": "unloaded_from_defroster", "name": "Выгружено из дефростера"},
    {"codename": "storekeeper_output", "name": "Ввод фактического веса каждого сырья"},
    {"codename": "storekeeper_outputed", "name": "Завершение ввода фактического веса сырья"},
    {"codename": "rastarshik_unload_mix_meat", "name": "Растарка замеса"},
    {"codename": "rastarshik_unload_mix_meat_end", "name": "Растарка замеса завершена"},
    {"codename": "press_operator_mix_meat", "name": "Сепарирование замеса"},
    {"codename": "press_operator_mix_meat_end", "name": "Сепарация замеса завершена"},
    {"codename": "mixer_mix_meat", "name": "Перемешивание и анализ замеса"},
    {"codename": "mixer_mix_meat_end", "name": "Завершение перемешивания и анализа замеса"},
    {"codename": "mixer_tiller_mix_meat", "name": "Загрузка в плиточник"},
    {"codename": "mixer_tiller_mix_meat_end", "name": "Загрузка в плиточник завершена"},
    {"codename": "laboratory_analyze", "name": "ФХП анализ"},
    {"codename": "laboratory_analyze_finish", "name": "Завершение ФХП анализа"},
    {"codename": "laboratory_analyze_technolog_acception", "name": "Проверка замеса главным технологом"},
    {"codename": "laboratory_analyze_again", "name": "Повторный анализ замеса"},
    {"codename": "mix_is_blocked_analyze", "name": "Замес заблокирован"},
    {"codename": "pallet_is_set", "name": "Перемещен на паллет"},
)

STATUS_QUEUE = {
    "created": ["defrosting"],
    "defrosting": ["separation"],
    "separation": ["bone_collection", "meat_microbiology_control_pass", "meat_microbiology_control_not_pass"],
    "bone_collection": ["bone_freezing"],
    "bone_freezing": ["bone_storage"],
    "bone_storage": ["bone_realization"],
    "meat_microbiology_control_not_pass": ["meat_adding_raw_materials"],
    "meat_adding_raw_materials": ["meat_microbiology_control_pass"],
    "meat_microbiology_control_pass": ["meat_mixing_minced_mmo", "meat_formation_briquettes"],
    "meat_mixing_minced_mmo": ["meat_tiler", "meat_aftercooling"],
    "meat_tiler": ["meat_packing_minced"],
    "meat_aftercooling": ["meat_packing_minced"],
    "meat_packing_minced": ["meat_formation_briquettes"],
    "meat_formation_briquettes": ["meat_shocker_freezing"],
    "meat_shocker_freezing": ["meat_metal_detection"],
    "meat_metal_detection": ["meat_palletizing"],
    "meat_palletizing": ["meat_storage"],
    "meat_storage": ["meat_shipment"],
}
